name: CI/CD - Build & Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t saedismail/myapp .

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: |
        docker push saedismail/myapp

    - name: SSH into EC2 and Deploy Container
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.KEY }}
        script: |
          docker pull saedismail/myapp
          docker rm -f myapp || true
          docker run -d --name myapp -p 80:3000 saedismail/myapp

